name: Aleo JS CI
on: push
jobs: 
  check-formatting:
    runs-on: [self-hosted]
    name: Check Formatting 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - run: npm ci
      - run: npx prettier --check .
  
  lint:
    runs-on: [self-hosted]
    name: Run Linters
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
        
      - run: npm ci
      - run: npx eslint .

