name: Publish Package to NPM
on:
  release:
  types: [published]
  jobs:
    build:
      runs-on: [self-hosted]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.release.target_commitish }}
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: "18"
            registry-url: "https://registry.npmjs.org"
        - name: Install dependencies
          run: npm ci
        - name: Build 
          run: npm run build
        - name: Update package version
          run: npm version ${{ github.event.release.tag_name }}
        - name: Publish Package on NPM
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
